kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-volume-claim
  namespace: starfleet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fast-new
