apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
    app: nginx
  namespace: starfleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        service: nginx
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: ceph-volume
          mountPath: /nginx
          readOnly: false
      volumes:
      - name: ceph-volume
        persistentVolumeClaim:
          claimName: ceph-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: starfleet
  labels:
    name: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    name: registry
  type: NodePort
