kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-pv-claim
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
