apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::782253790350:role/_ec2_testing_role
      labels:
        app: redis-deployment
    spec:
      containers:
      - name: redis
        image: redis:latest
