kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pypi-pv-claim
  namespace: pypi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
