apiVersion: apps/v1
kind: Deployment
metadata:
  name: pypi
  labels:
    name: pypi
    app: pypi
  namespace: pypi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pypi
  template:
    metadata:
      labels:
        service: pypi
        app: pypi
    spec:
      containers:
      - name: pypi
        image: pypiserver/pypiserver:v1.4.2
        volumeMounts:
        - name: pypi
          mountPath: /packages
          readOnly: false
        - name: htpasswd
          mountPath: /packages/.htpasswd
          subPath: .htpasswd
        args: ["-P", "/packages/.htpasswd", "-a", "update,download"]
      volumes:
      - name: pypi
        persistentVolumeClaim:
          claimName: pypi-pv-claim
      - name: htpasswd
        configMap:
          name: passwd
---
apiVersion: v1
kind: Service
metadata:
  name: pypi
  labels:
    service: pypi
  namespace: pypi
spec:
  selector:
    service: pypi
  type: ClusterIP
  ports:
  - port: 8080
