---
- name: power cycle starfleet vms
  hosts: "{{ hosts }}"
  tasks:
  
    - name: shutdown vm
      shell: shutdown -h now
      when: action == "shutdown"
      become: yes

    - name: reboot vm
      shell: shutdown -r now
      when: action == "reboot"
      become: yes
