---
- name: upgrade starfleet
  hosts: "{{ hosts }}"
  tasks:
  
    - name: upgrade apt
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      become: yes
